/* Official paper codes and legacy profile aliases. See docs/CONTENT.md. */
export const paperNames = {
  AE: "Aerospace Engineering",
  AG: "Agricultural Engineering",
  AR: "Architecture and Planning",
  BM: "Biomedical Engineering",
  BT: "Biotechnology",
  CE: "Civil Engineering",
  CH: "Chemical Engineering",
  CS: "Computer Science & Information Technology",
  CY: "Chemistry",
  DA: "Data Science & Artificial Intelligence",
  EC: "Electronics & Communication Engineering",
  EE: "Electrical Engineering",
  ES: "Environmental Science & Engineering",
  EY: "Ecology and Evolution",
  GE: "Geomatics Engineering",
  GG: "Geology & Geophysics",
  IN: "Instrumentation Engineering",
  MA: "Mathematics",
  ME: "Mechanical Engineering",
  MN: "Mining Engineering",
  MT: "Metallurgical Engineering",
  NM: "Naval Architecture & Marine Engineering",
  PE: "Petroleum Engineering",
  PH: "Physics",
  PI: "Production & Industrial Engineering",
  RA: "Robotics & Automation",
  ST: "Statistics",
  XE: "Engineering Sciences",
  XH: "Humanities & Social Sciences",
  XL: "Life Sciences",
  TF: "Textile Engineering & Fibre Science (2026 archive)",
};
export const branchAliases = {
  ECE: "EC",
  CSE: "CS",
  Mechanical: "ME",
  Civil: "CE",
  AIML: "DA",
  Cybersecurity: "CS",
};
export const branches = [
  "ECE",
  "CSE",
  "Mechanical",
  "Civil",
  "AIML",
  "Cybersecurity",
  "AE",
  "AG",
  "AR",
  "BM",
  "BT",
  "CE",
  "CH",
  "CS",
  "CY",
  "DA",
  "EC",
  "EE",
  "ES",
  "EY",
  "GE",
  "GG",
  "IN",
  "MA",
  "ME",
  "MN",
  "MT",
  "NM",
  "PE",
  "PH",
  "PI",
  "RA",
  "ST",
  "XE",
  "XH",
  "XL",
  "TF",
];
export const paperForBranch = (branch) => branchAliases[branch] || branch;
export const branchLabel = (branch) =>
  branch in branchAliases
    ? `${branch} · ${branchAliases[branch]}`
    : `${branch} · ${paperNames[branch] || branch}`;
